### ISSUE TITLE
more sophisticated sorting

### ISSUE THREAD

**Issue by port19x** [rcj/consult-ls-git#2]
Hi, I believe it would be a good idea to rank unstaged, unmodified files by count of commits involving that file.
That way, relevant files are shown at- or near the top of completion, which fits well with this projects goal and ux

**Comment by rcj** [comment]
Is there a way to get this information cheaply? Especially on larger repositories I expect this to be a potential expensive operation?

**Comment by port19x** [comment]
Certainly not with the usual interactive commands like `git log` or `git status`.
I'll look into possible avenues over the weekend. `git reflog` is one that immediately comes to mind, but there is probably something better

**Comment by port19x** [comment]
I'm putting this on the backlog for now.
If anyone stumbles upon the issue in the mean time, a good idea would be a limited history based on commit-count

**Comment by port19x** [comment]
I just revisited the idea.
A naive approach would be to count the frequency of occurences in the git log like so:
`time for i in $(git ls-tree -r HEAD | cut -f 2); do echo "$(git log -- $i | wc -l) - $i"; done | sort -n`

This takes 1.2 seconds on my pretty strong laptop and isn't even that much more sophisticated.
I'm closing this
